apiVersion: v1
kind: Pod
metadata:
  name: meupod
spec:
  containers:
    - name: web
      image: phalkao/web-flask:v1
      ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Pod
metadata:
  name: meupod-label
  labels:
    app: web
spec:
  containers:
    - name: web
      image: phalkao/web-flask:v1
      ports:
        - containerPort: 5000
